### PR TITLE
 Milestone 1: Create and incorporated"Linters" in a project

### PR DESCRIPTION
**Pull request by mdg0410**
## Incorporated Linters milestone 1: Create and incorporated "Linters" in a project

In this milestone: 
- Create a .github/workflows folder and add a copy of [.github/workflows/linters.yml](https://github.com/microverseinc/linters-config/blob/master/html-css/.github/workflows/linters.yml) to that folder.
- Create .gitignore to the root directory of your project and add `node_modules/` & `test.md`
- Incorporating Webhint
- Incorporating Stylelint
- Created index.html
- Created styles.css
- Created test.md

## [Webhint](https://webhint.io/)
A customizable linting tool that helps you improve your site's accessibility, speed, cross-browser compatibility, and more by checking your code for best practices and common errors.
- If running on Windows , you need to initialize npm to create package.json file. `npm init -y`
1. run `npm install --save-dev hint@7.x`
2. Copy [.hintrc](https://github.com/microverseinc/linters-config/blob/master/html-css/.hintrc) to the root directory of your project.
3. Run `npx hint .` for check the errors
4. If is necesary, run `npx hint . --fix` for correct errors

## [Stylelint](https://stylelint.io/)
A mighty, modern linter that helps you avoid errors and enforce conventions in your styles.
1. Run `npm install --save-dev stylelint@13.x stylelint-scss@3.x stylelint-config-standard@21.x stylelint-csstree-validator@1.x`
2. Copy [.stylelintrc.json](https://github.com/microverseinc/linters-config/blob/master/html-css/.stylelintrc.json) to the root directory of your project. 
3. Run `npx stylelint "**/*.{css,scss}"`  for check the errors
4. If is necesary, run `npx stylelint "**/*.{css,scss" --fix` for correct errors

### CODE REVIEW

**Review by huseyinbiyik — CHANGES_REQUESTED** [review]
Hi @mdg0410,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
Almost there

## Highlights
- Linter set up well and checks pass 🟢
- Github flow followed 👌
- .gitignore used to ignore requested files 📁
- Commit messages are meaningful and written in imperative tense 📝

## Required Changes ♻️
❗️❗️ Please don't delete any branch till your Pull Request is approved. Make your changes on this branch. Currently, I need to re-review this project according to the previous reviewer's requests, but unfortunately, you deleted the branch and I need to review It from the beginning.
- Please use descriptive branch names instead of "feature" (e.g.: project-setup, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. [Check](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md) more to learn more about this.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mdg0410** [comment]
@huseyinbiyik Done I have changed the branch name to a more descriptive name and have redone the pull request
I also did not delete any branches 

I have a doubt, after this correction you can approve the project or I have to re-request the revision in the dashboard?

**Comment by huseyinbiyik** [comment]
Hey @mdg0410, your branch name is still "feature". You can check the GIF I shared to learn how to change the branch name. When you are done, you can submit your pull request from dashboard.

**Comment by mdg0410** [comment]
Hey @huseyinbiyik 

I renamed it but it created another branch with the new name and I made the pull request to that branch.
https://github.com/mdg0410/Hello-World/pull/3

Can you help me please, I am about to lose all the extra revisions.
Give me some advice on how to get through please.

**Pull request closed without merging**
